// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBilp70tOu7E32ra_DokeQ5xvoM5Pl29ls',
    appId: '1:675470974343:web:631abcabfa844a2a048722',
    messagingSenderId: '675470974343',
    projectId: 'ioit-acm',
    authDomain: 'ioit-acm.firebaseapp.com',
    databaseURL: 'https://ioit-acm-default-rtdb.firebaseio.com',
    storageBucket: 'ioit-acm.appspot.com',
    measurementId: 'G-QMNCXS468Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXvESzoQpdUoARsU7AaGn4yq0ZgWx20qk',
    appId: '1:675470974343:android:9f76c5a3531388c1048722',
    messagingSenderId: '675470974343',
    projectId: 'ioit-acm',
    databaseURL: 'https://ioit-acm-default-rtdb.firebaseio.com',
    storageBucket: 'ioit-acm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2sFgXkuJ_IJjxFU7kFPA7iqFrFE3w4no',
    appId: '1:675470974343:ios:aefdd805ce61fc8c048722',
    messagingSenderId: '675470974343',
    projectId: 'ioit-acm',
    databaseURL: 'https://ioit-acm-default-rtdb.firebaseio.com',
    storageBucket: 'ioit-acm.appspot.com',
    iosBundleId: 'com.example.acmIoit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2sFgXkuJ_IJjxFU7kFPA7iqFrFE3w4no',
    appId: '1:675470974343:ios:0a846b4c20a41643048722',
    messagingSenderId: '675470974343',
    projectId: 'ioit-acm',
    databaseURL: 'https://ioit-acm-default-rtdb.firebaseio.com',
    storageBucket: 'ioit-acm.appspot.com',
    iosBundleId: 'com.example.acmIoit.RunnerTests',
  );
}
